[versions]

angus-mail = "2.0.3"
clikt = "5.0.1"
jsoup = "1.18.1"
junit5 = "5.11.2"
kotlin = "2.0.21"
logback-classic = "1.5.9"
simple-ocr = "1.3.0"

[libraries]

angus-mail = { module = "org.eclipse.angus:angus-mail", version.ref = "angus-mail"}
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt"}
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup"}
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5"}
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5"}
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic"}
simple-ocr = { module = "org.hildan.ocr:simple-ocr", version.ref = "simple-ocr"}

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
